/*******************************************************************************
* MIT License
*
* Copyright (c) 2021 Clayton Craig
*  
* Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
*  
* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*******************************************************************************/

/*******************************************************************************
* Header
*******************************************************************************/
var AC = {
    "Autos": {},
    "Cache": {
		"Auto": {}
	},
    "Config": {},
    "Data": {},
    "Helper": {},
    "Mod": {},
    "Version": "2.031/5"
}

/*******************************************************************************
* AC
*
* These functions are used by Cookie Clicker to run the game
*******************************************************************************/
/*
* This function is called by Cookie Clicker to initialize the mod
*/
AC.init = function() {
    if (Game.prefs.popups) {Game.Popup("Auto Cookie " + AC.Version + " loaded.")} else {Game.Notify("Auto Cookie " + AC.Version + " loaded.", "", "", 1, 1)}
    Game.Win("Third-party");
	
	for (const f in AC.Auto) {
		AC.Cache.Auto[f] = {}
	}
}

/*
* This function returns AC.Config.current as a stringified JSON as requested by Cookie Clicker
*/
AC.save = function() {
    return JSON.stringify(AC.Config.current);
}

/*
* This function loads AC.Config.current from the save data provided by Cookie Clicker
* @param	{str}	saveStr	Setting data in the same format as AC.Config.default as a stringified JSON
*/
AC.load = function(saveStr) {
    AC.Config.loaded = AC.Config.default;
	
    try {
        var settings = JSON.parse(saveStr);
        for (const property in settings) {
            if (AC.Config.default.hasOwnProperty(property)) {
                AC.Config.loaded[property] = settings[property];
            }
        }
    } catch(err) {
        AC.Config.loaded = AC.Config.default;
    }
	
    AC.startAutos(AC.Config.loaded);
}

/*
* This function sets the intervals that the functions in AC.Auto are called at
*/
AC.startAutos = function() {
	for (constf in AC.Auto) {
		if (typeof AC.Cache.Auto[f].ID !== "undefined") {AC.Cache.Auto[f].ID = clearInterval(AC.Cache.Auto[f])} else {AC.Cache.Auto[f].ID = undefined}
		if (AC.Config.current.Auto[f].interval != 0) {AC.Cache.Auto[f].ID = setInterval(AC.Auto[f], AC.Config.current.Auto[f].interval)}
	}
}

/*******************************************************************************
* AC.Auto
*
* Functions that are called by AC.startAutos() to automatically perform game actions
*
* For each AC.Auto.f, the following data is generated
*	AC.Cache.Auto.f   	{dict}	Generated by AC.init(), stores any local information required by f between calls
*	AC.Cache.Auto.f.ID	{num} 	Generated by AC.startAutos(), stores the ID used by clearInterval() to stop the function from being called
*
* For each AC.Auto.f, unique settings should be stored in the following places as a dictionary
*	AC.Config.default.Auto.f	{dict}	The default settings
*	AC.Config.current.Auto.f	{dict}	The current settings
*	AC.Config.maximum.Auto.f	{dict}	The maximum settings (must be greater than the minimum settings)
*	AC.Config.minimum.Auto.f	{dict}	The minimum settings (must be less than the maximum settings)
*
* For each AC.Auto.f, the following data is expected
*	AC.Config.default.Auto.f.interval	{num}	The default interval (in ms) at which to call f. If == 0, f is not called by default
*	AC.Config.current.Auto.f.interval	{num}	The current interval (in ms) at which to call f. If == 0, f is not called
*	AC.Config.maximum.Auto.f.interval	{num}	The maximum interval (in ms) at which to call f. If == 0, f is assumed to not be called, but might if the user's save data is old
*	AC.Config.minimum.Auto.f.interval	{num}	The minimum interval (in ms) at which to call f. If == 0, f is not necessarily called
*******************************************************************************/
/*
* This function clicks the cookie a number of times
*/
AC.Auto.clickCookie = function() {
	for (var i = 0; i < AC.Config.current.Auto.clickCookie.numClicks; i++) {Game.ClickCookie()}
}

/*******************************************************************************
* AC.Cache
*
* Data that is generated during runtime
*******************************************************************************/

/*******************************************************************************
* AC.Config
*
* Functions and dictionaries that store the confriguration of this mod
*******************************************************************************/
AC.Config.default = {
	"Auto": {
		"clickCookie": {
			"numClicks": 5
		}
	}
}

AC.Config.maximum = {
	"Auto": {
		"clickCookie": {
			"numClicks": 250
		}
	}
}

AC.Config.minimum = {
	"Auto": {
		"clickCookie": {
			"numClicks": 0
		}
	}
}

AC.Config.current = AC.Config.default;

/*******************************************************************************
* AC.Data
*
* Data that is created before runtime
*******************************************************************************/

/*******************************************************************************
* AC.Lib
*
* Additional functions that aid in other calculations.
*******************************************************************************/

/*******************************************************************************
* Register the mod with Cookie Clicker
*******************************************************************************/
Game.registerMod("AutoCookieBeta", AC);
